# This workflow runs edgetest on edgetest-hub @ 17:35 UTC Fridays.
# https://github.com/fdosani/run-edgetest-action

name: Run edgetest
on:
  schedule:
    - cron: '35 17 * * 5'
jobs:
  edgetest:
    runs-on: ubuntu-latest
    name: running edgetest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - id: run-edgetest
        uses: fdosani/run-edgetest-action@v1.3
        with:
          edgetest-flags: '-c setup.cfg --export'
          base-branch: 'dev'
          skip-pr: 'false'
          python-version: '3.10'
